server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: jwt
          uri: https://github.com/rosemberg0212/microservicios-proyecto
          search-paths: config-data
  application:
    name: config-server
